name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: iris-rf
      IMAGE_TAG: latest
      DOCKER_REPO: rohikam/iris-rf

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow scikit-learn pandas

    - name: Run MLflow Training & Register Model
      run: |
        python tracking.py
        python registermodel.py

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $DOCKER_REPO:$IMAGE_TAG .

    - name: Push Docker image
      run: docker push $DOCKER_REPO:$IMAGE_TAG

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.EKS_KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        # kubectl delete -f inference-service.yaml || true
        kubectl apply -f k8s.yaml
