name: Deploy to K8s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-iris:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops-iris:latest

    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment/k8s-deployment.yaml
        kubectl apply -f deployment/k8s-service.yaml
